project:
  type: website
  output-dir: docs

website:
  title: "MODEL EVALUATION SYSTEM"
  navbar:
      background: primary
      search: true
      right:
        - text: "Species for Evaluation"
          menu:
            - text: "Home"
              href: index.qmd

format:
  html:
    theme: Sandstone
    page-layout: article
    toc: false
    css: styles.css
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
    

editor: visual